### ISSUE TITLE
mqtt plugin

### ISSUE THREAD

**Issue by starfish1107** [gotify/contrib#11]
a mqtt-client plugin subscribing to a topic on a configurable broker would be very desirable and useful espescially for iot applications.

**Comment by tystuyfzand** [comment]
I know this is super old but I like this idea. I'll throw something together this weekend probably if you're still interested - could definitely use it with my D1 Minis.

**Comment by starfish1107** [comment]
just great. looking forward 

Am 21. Juli 2021 05:41:36 MESZ schrieb Tyler Stuyfzand ***@***.***>:
>I know this is super old but I like this idea. I'll throw something
>together this weekend probably if you're still interested - could
>definitely use it with my D1 Minis.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gotify/contrib/issues/11#issuecomment-883862370

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tystuyfzand** [comment]
See https://github.com/tystuyfzand/gotify-mqtt/releases/tag/v1.0.0 - PR opened to add it to contrib as well :)
