### ISSUE TITLE
Add GotifySharp and GotifyDesktop to list.

### ISSUE THREAD

**Issue by ajmcateer** [gotify/contrib#12]
Hi Author of GotifySharp and GotifyDesktop here any chance you could add my repositories to the list.

https://github.com/ajmcateer/GotifyDesktop
https://github.com/ajmcateer/GotifySharp

**Comment by jmattheis** [comment]
Sure think, could you file a pull request with the new entries?

**Comment by ajmcateer** [comment]
PR filed
