### ISSUE TITLE
Ready for build iOS, JavaScript SDK

### ISSUE THREAD

**Issue by Husseinhj** [gotify/contrib#17]
I have experience in push notification and marketing platforms and develop on Android, iOS, Javascript (VAPID), and hybrid platforms which has support push notification.

If you are interested, I'm OK.

**Comment by jmattheis** [comment]
Contributions are welcome, do you already have something specific in mind what you want to do?

**Comment by Husseinhj** [comment]
I think we should talk about the priority of which platform can help us to make the Gotify multi-platform supports.
It depended on back-end priority to choose which implementation (APNs or VAPID) has high priority.
Based on my experience, I think the APNs is easy to start.

**Comment by jmattheis** [comment]
An iOS app is pretty much impossible due to restrictions from apple. See https://github.com/gotify/server/issues/87
I don't really know what you mean with VAPID, do you mean the CMS?

**Comment by Nicolasery** [comment]
But even if Gotify "can't" respect totally the apple rules, could you release an app for jailbreak users ? maybe with enough users their policy could change

**Comment by Husseinhj** [comment]
> An iOS app is pretty much impossible due to restrictions from apple. See [gotify/server#87](https://github.com/gotify/server/issues/87)

By using push notification to send messages to the apple devices and when the application opened, connecting to the server with MQTT or WebSocket. Something like [CataPush](https://www.catapush.com/) service.

> I don't really know what you mean with VAPID, do you mean the CMS?

VAPID technology [documentation](https://blog.mozilla.org/services/2016/08/23/sending-vapid-identified-webpush-notifications-via-mozillas-push-service/) for get push notification in Web.

**Comment by jmattheis** [comment]
> By using push notification to send messages to the apple devices 

With push notifications you mean use the APN? Gotify must not depend on any third-party services.

> But even if Gotify "can't" respect totally the apple rules, could you release an app for jailbreak users ? maybe with enough users their policy could change

That would be possible, but I don't think this would be worth the development effort, tho if someone wants to do this, feel free.

I see gotify as an alternative to web push notifications.

**Comment by starfish1107** [comment]
>  Gotify must not depend on any third-party services.
> ... 
> I see gotify as an alternative to web push notifications.

this is imho the main advantage of gotify  and the reason I am using it.  But OK, it would be desirable to have a mqtt listener plugin.

**Comment by Husseinhj** [comment]
> With push notifications you mean use the APN? Gotify must not depend on any third-party services.

In my opinion, If Gotify wants to be popular and supports all platforms, the best choice is to support APNs, WNS, and WebPush by sending messages while the app is in the background or terminated.

**Comment by Kami-no** [comment]
If notifications for messengers in iOS are available then it should be possible.

**Comment by pwFoo** [comment]
Would it possible to optional use third party apns? Would be ok for users anyway use browser of that vendors? Push message (content / text) should be encrypted I think?
https://github.com/gotify/server/issues/344#issuecomment-803971746

**Comment by jmattheis** [comment]
It would be possible, but I don't think it would align with the goals of gotify. So I'd see it as a community project and not officially supported from the gotify project.

The use of browsers is different, as messages (probably) don't get transmitted through third-party servers.

**Comment by pwFoo** [comment]
Maybe I'm wrong, but would https://github.com/web-push-libs help?
Go lib available too: https://github.com/SherClockHolmes/webpush-go

Should that libs help to handle vender specific (Google / Android, Mozilla / Firefox, Microsoft / Edge and Apple Safari, NOT iPhone) push notifications?

**Comment by jmattheis** [comment]
Maybe, but only when there is a fair amount of need from the community, https://github.com/gotify/server/issues/344 hasn't received many interactions.

**Comment by pwFoo** [comment]
That feature would add new use cases. Would be possible to add push notifications to desktop browser (windows, linux and mac) and android.

**Comment by jmattheis** [comment]
Sure, but gotify already supports this to some degree, there is an android app and when the web ui is open, it'll show browser push notifications.

The benefit would be, that browser push notifications would work, even if the ui isn't open.
