### ISSUE TITLE
Gotify GNOME client

### ISSUE THREAD

**Issue by kisst** [gotify/contrib#55]
Before I send a PR just wanted to check does this belong here https://github.com/kisst/gotify-gnome-client ?

**Comment by jmattheis** [comment]
Yeah, this fits into this repo. Maybe you could add a little more description what the project does and why it's useful into the Readme, it wasn't that obvious to me at first read. Something like "Show gotify messages as gnome notifications" or similar.

**Comment by kisst** [comment]
Add a screenshot and updated the first line of readme https://github.com/gotify/contrib/pull/56
